title: Jonathan Galan
#logo:https://media.licdn.com/dms/image/C4D03AQGvK77gvoALJQ/profile-displayphoto-shrink_800_800/0/1648233126527?e=1704326400&v=beta&t=yoUOc447fDF89rNhSURfINmXKb9vojPzYDlmAzerKr4
#description: Data Science
show_downloads: True
theme: jekyll-theme-minimal

